version: '3'

volumes:
  static_files:
  media_files:
#  cert_files:
services:
  python:
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=orwell.settings.prod
    volumes:
      - .:/orwell
      - static_files:/static_files
      - media_files:/media_files
    ports:
      - 8000:8000
    command: gunicorn -w 4 orwell.wsgi -b 0.0.0.0:8000

  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
#    - cert_files:/etc/nginx/conf.d/cert:ro
    - static_files:/static_files
    - media_files:/media_files
    depends_on:
      - python

    ports:
    - 80:80
    - 443:443
